import pulp
from app.query import fetch_menu_items

# 1. The "Virtual Menu" (Generated by your AI step)
offerings = fetch_menu_items(1)
print("Offerings fetched for LP Solver:", offerings)

# maximize convenience score
# maximizing sum of (x_i * convenience_score_i)
# main constraints (defaults to get from external library):
# total calories 
# total protein
# total carbs
# total fats